# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0003_auto_20160127_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('reso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Reservation')),
            ],
        ),
    ]
