# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reso',
        ),
        migrations.AddField(
            model_name='message',
            name='picture',
            field=models.URLField(default='https://i.imgur.com/WBdUBl0.jpg'),
        ),
        migrations.AddField(
            model_name='message',
            name='posted_by',
            field=models.CharField(default='<unknown person>', max_length=100),
            preserve_default=False,
        ),
    ]
