# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 23:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=10, unique=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('guest', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
