# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='thread_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
