# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20160127_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_reso', models.CharField(blank=True, max_length=10, unique=True)),
                ('thread_id', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=30, unique=True)),
                ('picture', models.URLField(default='https://i.imgur.com/WBdUBl0.jpg')),
                ('guest', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
