# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='label',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
