# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20160202_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='guest',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
