# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-29 03:11
from __future__ import unicode_literals

from django.db import migrations


def create_log_entries(apps, schema_editor):
    ReservationLog = apps.get_model("guests", "ReservationLog")
    Reservation = apps.get_model("guests", "Reservation")
    for reso in Reservation.objects.all():
        ReservationLog.objects.create(confirmation_code=reso.confirmation_code, action='send_accept_msg')


def delete_log_entries(apps, schema_editor):
    ReservationLog = apps.get_model("guests", "ReservationLog")
    ReservationLog.objects.filter(action='send_accept_msg').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_reservationlog'),
    ]

    operations = [
        migrations.RunPython(create_log_entries, delete_log_entries),
    ]
